global using System;
global using System.Linq;
global using System.Collections;
global using System.Collections.Generic;
global using CreativeCoders.Core;
global using CreativeCoders.Core.Comparing;
global using CreativeCoders.Git.Abstractions;
global using LibGit2Sharp;
global using JetBrains.Annotations;
